#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jBCrypt
Version  : 0.3m
Release  : 1
URL      : https://github.com/jeremyh/jBCrypt/archive/jbcrypt-0.3m.tar.gz
Source0  : https://github.com/jeremyh/jBCrypt/archive/jbcrypt-0.3m.tar.gz
Source1  : http://repo1.maven.org/maven2/org/mindrot/jbcrypt/0.3m/jbcrypt-0.3m.jar
Source2  : http://repo1.maven.org/maven2/org/mindrot/jbcrypt/0.3m/jbcrypt-0.3m.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : ISC
Requires: mvn-jBCrypt-data = %{version}-%{release}
Requires: mvn-jBCrypt-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
# JBCrypt
jBCrypt is an implementation the OpenBSD Blowfish password hashing algorithm,
as described in ["A Future-Adaptable Password
Scheme"](http://www.openbsd.org/papers/bcrypt-paper.ps) by Niels Provos and
David Mazieres.

%package data
Summary: data components for the mvn-jBCrypt package.
Group: Data

%description data
data components for the mvn-jBCrypt package.


%package license
Summary: license components for the mvn-jBCrypt package.
Group: Default

%description license
license components for the mvn-jBCrypt package.


%prep
%setup -q -n jBCrypt-jbcrypt-0.3m

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-jBCrypt
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-jBCrypt/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/mindrot/jbcrypt/0.3m
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/mindrot/jbcrypt/0.3m/jbcrypt-0.3m.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/mindrot/jbcrypt/0.3m
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/mindrot/jbcrypt/0.3m/jbcrypt-0.3m.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/mindrot/jbcrypt/0.3m/jbcrypt-0.3m.jar
/usr/share/java/.m2/repository/org/mindrot/jbcrypt/0.3m/jbcrypt-0.3m.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-jBCrypt/LICENSE
